version: '2'

linters:    
  default: all
  disable:
    # Disable overly strict or impractical linters
    - depguard           # Allow all imports (too restrictive for this project)
    - err113             # Allow dynamic errors (static errors not always practical)
    - exhaustruct        # Don't require all struct fields (too verbose)
    - exhaustive         # Don't require all switch cases (allow default handling)
    - godox              # Allow TODO/FIXME comments
    - gomoddirectives    # Allow local replace directives (needed for multi-module projects)
    - noctx              # Allow HTTP calls without context (not always needed)
    - nlreturn           # Don't require blank line before return (personal preference)
    - paralleltest       # Don't require t.Parallel() (may not be needed for all tests)
    - testpackage        # Allow tests in same package (white-box testing)
    - varnamelen         # Allow short variable names (standard Go practice)
    - wsl    
    - wsl_v5            # Whitespace linter (too opinionated)
    - tagliatelle        # Don't enforce tag naming convention (allow snake_case for JSON)
    - mnd                # Don't flag magic numbers (sometimes constants are overkill)
    - perfsprint         # Don't enforce fmt.Sprintf vs string concat (micro-optimization)
    - intrange           # Don't require Go 1.22+ range syntax (compatibility)
    - lll                # Don't enforce line length (some lines need to be long)
    - gochecknoglobals   # Allow globals when needed (e.g., sync.Once)
    - godot              # Don't enforce periods in comments (too strict)
    - errname            # Don't enforce error naming convention
    - nestif             # Don't flag nested if statements
    - whitespace         # Don't enforce whitespace rules
    - gosec              # Disabled due to SSA panic in golangci-lint v2.x
  settings:
    cyclop:
      max-complexity: 20
    errcheck:
      check-type-assertions: true
      check-blank: false
    funlen:
      lines: 200
      statements: 100
    gocyclo:
      min-complexity: 40
    goconst:
      min-len: 3
      min-occurrences: 3
    revive:
      rules:
        - name: var-naming
          disabled: true  # Allow package names like "utils"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
